/**
  *********************************************************************************
  *
  * @file    sdk_conf.h
  * @brief   Configuration header file
  * @date    2020/07/03 
  * @author  Eastsoft
  * @note    This file is autogenerated by ESBLETool
  *           Do not modify
  * Copyright (C) Shanghai Eastsoft Microelectronics Co. Ltd. All rights reserved.
  *
  *********************************************************************************
  */

#ifndef _SDK_CONF_H_
#define _SDK_CONF_H_

/**
  *********************************************************************************
  * @addtogroup SDK_config
  * @{
  * @name Common_config
  * @{ The following constants used to configure BLE Common parameters
  *********************************************************************************
  */

//#define CFG_ALLROLES
#define BLE_CFG_ROLE	ESBLE_ROLE_ALL
#define CFG_SEC_CON
#define CFG_CON 8
#define CFG_HCITL
#define CFG_HCI 0

/// @} Common_config

/**
  *********************************************************************************
  * @name PlatForm_config
  * @{ The following constants used to configure BLE PlatForm parameters
  *********************************************************************************
  */

#define BLE_LOG_RTT 1
#define BLE_LOG_UART 0
#define BLE_BD_ADDR {{0x11,0x22,0x45,0x67,0x89,0xab}}
#define BLE_SLP_ALGO_DUR 400
#define BLE_LPC_DRIFT 500
#define BLE_OSC_WUP_TIME 5000
#define BLE_MAX_SLEEP_DURATION_TIME 16000 //10s
#define BLE_LPC_32K_EN 0
#define BLE_CODED_PHY_500_EN 1
#define BLE_SLEEP_EN 0
#define BLE_EXT_WAKEUP_ENABLE 1
#define BLE_WL_MAX 4
#define BLE_RAL_MAX 3
#define BLE_DUP_FILT_MAX 10
#define BLE_CA_UPD_PER 4
#define BLE_CA_RSSI_THRD -70
#define BLE_CA_MAX_COUNT 4
#define BLE_CA_MIN_COUNT -4
#define BLE_CA_BAD_CH_THRD -2

/// @} PlatForm_config

/**
  *********************************************************************************
  * @name Device_config
  * @{ The following constants used to configure BLE Device parameters
  *********************************************************************************
  */

#define BLE_USE_RANDOM_ADDR 1
#define BLE_RANDOM_ADDR {{0xda,0x7a,0xbf,0x6d,0x34,0x01}}
#define BLE_PRIVACY		0
#define BLE_RENEW_DURATION 900
#define BLE_PAIR_MODE 			ESBLE_PAIRING_DISABLE
#define BLE_SUGG_MAX_TX_OCTETS	27
#define BLE_SUGG_MAX_TX_TIME	328
#define BLE_PREF_TX_PHY 7
#define BLE_PREF_RX_PHY 7
#define BLE_L2CAP_MAX_MTU		27
#define BLE_L2CAP_MAX_MPS		0
#define BLE_L2CAP_MAX_LECB_CONN	0
#define BLE_GAP_START_HDL 0
#define BLE_GATT_START_HDL 0
#define BLE_ATT_NAME_PERM 0
#define BLE_ATT_APPEARENCE_PERM	0
#define BLE_ATT_SLV_PREF_CON_PAR_EN 1
#define BLE_ATT_SVC_CHG_EN 0

#define BLE_DEV_LOCAL_NAME				"ESW3120-LED"
#define BLE_DEV_LOCAL_NAME_LEN			(sizeof(BLE_DEV_LOCAL_NAME))
#define BLE_DEV_LOCAL_APPEARANCE	0x0000

#define BLE_DEV_SLV_PREF_CONN_MIN_INTV	8
#define BLE_DEV_SLV_PREF_CONN_MAX_INTV	10
#define BLE_DEV_SLV_PREF_LATENCY		0
#define BLE_DEV_SLV_PREF_SUP_TO			200

#define BLE_DEV_WL {{0x66,0x55,0x44,0x33,0x22,0x11,0x00},{0x66,0x55,0x44,0x33,0x22,0x12,0x00},{0x66,0x55,0x44,0x33,0x33,0x12,0x00},{0x66,0x55,0x44,0x44,0x33,0x12,0x00}}
#define BLE_DEV_WL_NB 4
#define BLE_DEV_PSM {{0x34,0x12,0x04},{0x34,0x12,0x05}}
#define BLE_DEV_PSM_NB 2
#define BLE_LED_SERVER       1
#define BLE_LED_CLIENT       0
#define LIGHTS_UUID_128		1
#define BLE_SERVER_PRF          1
#define BLE_CLIENT_PRF          0
#define BLE_NB_PRF              5

/// @} Device_config

/**
  *********************************************************************************
  * @name Advertising_config
  * @{ The following constants used to configure BLE Advertising parameters
  *********************************************************************************
  */

#define BLE_ADV_OWN_ADDR_TYPE 0
#define BLE_ADV_TYPE 0
#define BLE_ADV_PROP 0x0001
#define BLE_ADV_MODE 1
#define BLE_ADV_FILTER 0
#define BLE_ADV_PAR_DURATION 0
#define BLE_ADV_PAR_TXPWR 0x7E
#define BLE_ADV_DATA {}
//{0x02,0x02,0x11,0x11,\
//                       0x02,0x09,0x34,0x56}
#define BLE_ADV_DATA_LEN 0
#define BLE_SCANRSP_DATA {0x05,0x02,0x11,0x22,0x33,0x44,0x09,0x19,0x55,0xaa,0x55,0xaa,0x55,0xaa,0x55,0xaa}
#define BLE_SCANRSP_DATA_LEN 0
#define BLE_ADV_PAR_PRIM_CFG_ADV_INTV_MIN 64
#define BLE_ADV_PAR_PRIM_CFG_ADV_INTV_MAX 64
#define BLE_ADV_PAR_PRIM_CFG_CHNL_MAP 0x07
#define BLE_ADV_PAR_PRIM_CFG_PHY 1
#define BLE_ADV_PAR_SECOND_CFG_PHY 1
#define BLE_ADV_PAR_PERIOD_CFG_ADV_INTV_MIN 100
#define BLE_ADV_PAR_PERIOD_CFG_ADV_INTV_MAX 120
#define BLE_ADV_CONN_UPD_EN 1
#define BLE_ADV_CONN_UPD_PAR_INTV_MIN 125
#define BLE_ADV_CONN_UPD_PAR_INTV_MAX 150
#define BLE_ADV_CONN_UPD_PAR_LATENCY 0
#define BLE_ADV_CONN_UPD_PAR_TIME_OUT 250
#define BLE_ADV_CONN_UPD_PAR_CE_MIN 0
#define BLE_ADV_CONN_UPD_PAR_CE_MAX 0

/// @} Advertising_config

/**
  *********************************************************************************
  * @name Scan_config
  * @{ The following constants used to configure BLE Scan parameters
  *********************************************************************************
  */

#define BLE_SCAN_OWN_ADDR_TYPE 0
#define BLE_SCAN_TYPE 0
#define BLE_SCAN_PROP 0x05
#define BLE_SCAN_PROP_FILT 0X00
#define BLE_SCAN_PAR_1M_SCAN_INTV 160
#define BLE_SCAN_PAR_1M_SCAN_WD 160
#define BLE_SCAN_PAR_CODED_SCAN_INTV 160
#define BLE_SCAN_PAR_CODED_SCAN_WD 160
#define BLE_SCAN_DURATION 0
#define BLE_SCAN_PERIOD 0
#define BLE_SCAN_FILTER_ENABLE 1
#define BLE_SCAN_NAME_CNT 0
#define BLE_SCAN_NAME_MAX_LEN 32
#define BLE_SCAN_UUID_CNT 1

/// @} Scan_config

/**
  *********************************************************************************
  * @name Initiator_config
  * @{ The following constants used to configure BLE Initiator parameters
  *********************************************************************************
  */

#define BLE_INIT_OWN_ADDR_TYPE 0
#define BLE_INIT_TYPE 0
#define BLE_INIT_PROP 0x07
#define BLE_INIT_PAR_CONN_TO 100
#define BLE_INIT_PEER_ADDR {{0x01,0x23,0x45,0x67,0x89,0xab},0x00 }
#define BLE_INIT_PAR_SCAN_PARAM_1M_SCAN_INTV 160
#define BLE_INIT_PAR_SCAN_PARAM_1M_SCAN_WD 40
#define BLE_INIT_PAR_CONN_PARAM_1M_CONN_INTV_MIN 8
#define BLE_INIT_PAR_CONN_PARAM_1M_CONN_INTV_MAX 16
#define BLE_INIT_PAR_CONN_PARAM_1M_CONN_LATENCY 0
#define BLE_INIT_PAR_CONN_PARAM_1M_SUPERVISION_TO 500
#define BLE_INIT_PAR_CONN_PARAM_1M_CE_LEN_MIN 0
#define BLE_INIT_PAR_CONN_PARAM_1M_CE_LEN_MAX 16000
#define BLE_INIT_PAR_SCAN_PARAM_CODED_SCAN_INTV 160
#define BLE_INIT_PAR_SCAN_PARAM_CODED_SCAN_WD 40
#define BLE_INIT_PAR_CONN_PARAM_2M_CONN_INTV_MIN 16
#define BLE_INIT_PAR_CONN_PARAM_2M_CONN_INTV_MAX 32
#define BLE_INIT_PAR_CONN_PARAM_2M_CONN_LATENCY 0
#define BLE_INIT_PAR_CONN_PARAM_2M_SUPERVISION_TO 3200
#define BLE_INIT_PAR_CONN_PARAM_2M_CE_LEN_MIN 0
#define BLE_INIT_PAR_CONN_PARAM_2M_CE_LEN_MAX 16000
#define BLE_INIT_PAR_CONN_PARAM_CODED_CONN_INTV_MIN 48
#define BLE_INIT_PAR_CONN_PARAM_CODED_CONN_INTV_MAX 96
#define BLE_INIT_PAR_CONN_PARAM_CODED_CONN_LATENCY 0
#define BLE_INIT_PAR_CONN_PARAM_CODED_SUPERVISION_TO 1000
#define BLE_INIT_PAR_CONN_PARAM_CODED_CE_LEN_MIN 0
#define BLE_INIT_PAR_CONN_PARAM_CODED_CE_LEN_MAX 80000

/// @} Initiator_config

/**
  *********************************************************************************
  * @name Period Sync_config
  * @{ The following constants used to configure BLE Period Sync parameters
  *********************************************************************************
  */

#define BLE_PER_SYNC_OWN_ADDR_TYPE 0
#define BLE_PER_SYNC_TYPE 1
#define BLE_PER_SYNC_PAL {{0x0b,0x9a,0x78,0x56,0x34,0x12,0x00}}
#define BLE_DEV_PAL_NB 1
#define BLE_PER_SYNC_SKIP 0
#define BLE_PER_SYNC_SYNC_TO 1000

/// @} Period Sync_config

/// @} SDK_config
#endif
